### ISSUE TITLE
BUG Sichtkontakt

### ISSUE THREAD

**Issue by ghost** [yoktobit/morzyn#3]
Ich (rosafarbener Zauber ... ZUFALL!) konnte den Gorilla, der mir nicht gehörte, mit einem Fernangriff angreifen. Ich stelle diese Situation aber noch nach und versuche, weitere Details zusammeln.

![unbenannt](https://cloud.githubusercontent.com/assets/15103150/10476024/54c8207e-724a-11e5-8877-12bb2399b2aa.png)

**Comment by yoktobit** [comment]
Neu: Von den jeweiligen Mittelpunkten der Felder der beiden Kreaturen wird eine Linie gebildet, deren Schnittpunkte mit den Quadraten berechnet werden. So sind keine überschneidenden Flächen mehr notwendig für die Berechnung und die Sichtbarkeit kann auch besser vom Spieler selbst erfasst werden.

**Comment by ghost** [comment]
Kann man Beiträge liken? :-) :+1:
