### ISSUE TITLE
Immunitäten

### ISSUE THREAD

**Issue by ghost** [yoktobit/morzyn#4]
Die Magier sind immun gegen jede Art von Elementarschaden. Das soll nicht für rein physische Schäden wie Bogen (Elvish Bowman) und Axt (Dwarf) gelten.

Momentan scheint es so, als würden diese Attacken ebenfalls ignoriert.

**Comment by yoktobit** [comment]
Hat mich auch stark irritiert, bis ich einen grünen Stern mit einer 2 gesehen habe, der eigentlich nie erscheinen dürfte...hier kam einfach der falsche (grüne) Stern.
