### ISSUE TITLE
Animation für Manatransfer

### ISSUE THREAD

**Issue by ghost** [yoktobit/morzyn#5]
Beim Auftreffen des Geschosses vom Manatransfer soll eine Animation abgespielt werden wie beim Schadensstern und dem Herz bei Heilung.

Diese Grafik reiche ich noch nach.

**Comment by ghost** [comment]
Update: Der blaue Stern soll als Animation beim Auftreffen der Manakugel erscheinen und enthält die übertragenen Manapunkte. Passiert momentan leider nicht, obwohl er bereits implementiert wurde. :-O

**Comment by yoktobit** [comment]
Der blaue Manastern war einfach komplett falsch implementiert
