### ISSUE TITLE
Heilung sollte immer erfolgreich sein

### ISSUE THREAD

**Issue by ghost** [yoktobit/morzyn#7]
Ich hatte eben den Fall, dass ich bei drei aufeinander folgenden Heilzaubern genau 0 Punkte geheilt habe - sehr ärgerlich. Bitte die Erfolgschance beim Heilzauber auf 100% stellen. Es sollen zwischen 3 und 5 Lebenspunkten regeneriert werden. Fehlschläge gibt es nicht.

**Comment by yoktobit** [comment]
War die Lebensenergie eventuell bei den bezauberten Kreaturen schon voll?

**Comment by ghost** [comment]
Nope, war für meinen Sorcerer, der dem Tode nah war.

**Comment by yoktobit** [comment]
Je mehr eine Einheit verwundet ist, desto weniger wurde geheilt, weil sich die Heilungsprozente nur auf die aktuelle Lebensenergie bezogen.
Festlegung: Zukünftig sollen die sich auf die bereits verbrauchte Lebensenergie beziehen, sodass man mehr heilt, je mehr Schaden schon genommen wurde.
